// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyrUoKLEG4-GSz9soBMGIfc-nJquBzk0',
    appId: '1:909709262691:web:822f463fadf73bcfcc1d56',
    messagingSenderId: '909709262691',
    projectId: 'login-register-8c7cc',
    authDomain: 'login-register-8c7cc.firebaseapp.com',
    storageBucket: 'login-register-8c7cc.firebasestorage.app',
    measurementId: 'G-SGSKTE513R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9Z9XNcHV-YD4VDWkKggzxH67mDAjzFA',
    appId: '1:909709262691:android:b4fa8a22b673b615cc1d56',
    messagingSenderId: '909709262691',
    projectId: 'login-register-8c7cc',
    storageBucket: 'login-register-8c7cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPuV5iZ7Bssh3lghC4OKViYesDuC9JY3E',
    appId: '1:909709262691:ios:6554fce4a2499af5cc1d56',
    messagingSenderId: '909709262691',
    projectId: 'login-register-8c7cc',
    storageBucket: 'login-register-8c7cc.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPuV5iZ7Bssh3lghC4OKViYesDuC9JY3E',
    appId: '1:909709262691:ios:6554fce4a2499af5cc1d56',
    messagingSenderId: '909709262691',
    projectId: 'login-register-8c7cc',
    storageBucket: 'login-register-8c7cc.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACyrUoKLEG4-GSz9soBMGIfc-nJquBzk0',
    appId: '1:909709262691:web:a53b618ddf549ddfcc1d56',
    messagingSenderId: '909709262691',
    projectId: 'login-register-8c7cc',
    authDomain: 'login-register-8c7cc.firebaseapp.com',
    storageBucket: 'login-register-8c7cc.firebasestorage.app',
    measurementId: 'G-7YY63DN1XK',
  );
}
